var courseData=
[
	{
      "id": 1,
      "name": "COVID-19 Contact Tracing",
      "img": "https://dl.dropboxusercontent.com/s/94nx60hwuk1xcvs/1.jpg?dl=0",
      "instructor": "Emily Gurley, PhD, MPH",
      "price": 9.99,
	  "rating": 4.9,
    },
	{
      "id": 2,
      "name": "Cisco CCNA 200-301 – The Complete Guide to Getting Certified",
      "img": "https://dl.dropboxusercontent.com/s/ewpz9hyo66y20vn/3.jpg?dl=0",
      "instructor": "Neil Anderson",
	  "rating": 4.8,
	  "price": 13.99,
    },
	{
      "id": 3,
      "name": "Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
      "img": "https://dl.dropboxusercontent.com/s/t3sd30o4ia8fvfq/2.jpg?dl=0",
      "instructor": "Jonas Schmedtmann",
	  "rating": 4.8,
	  "price": 24.99,
    },
	{
      "id": 4,
      "name": "2020 Complete Python Bootcamp: From Zero to Hero in Python",
      "img": "https://dl.dropboxusercontent.com/s/0l27b3jb9fc4ucy/4.jpg?dl=0",
      "instructor": "Jose Portilla",
	  "rating": 4.6,
	  "price": 9.99,
    },
	{
      "id": 5,
      "name": "React - The Complete Guide (incl Hooks, React Router, Redux)",
      "img": "https://dl.dropboxusercontent.com/s/qcrs8dgjyv665cc/8.jpg?dl=0",
      "instructor": "Academind by Maximilian Schwarzmüller, Maximilian Schwarzmüller",
	  "rating": 4.6,
	  "price": 15.99,
    },
	{
      "id": 6,
      "name": "Microsoft Excel - Excel from Beginner to Advanced",
      "img": "https://dl.dropboxusercontent.com/s/yo1uy9gz0r2l7gu/9.jpg?dl=0",
      "instructor": "Kyle Pew, Office Newb LLC",
	  "rating": 4.6,
	  "price": 14.99,
    },
	{
      "id": 7,
      "name": "Learn Python Programming Masterclass",
      "img": "https://dl.dropboxusercontent.com/s/eia2xgp95pgw394/10.jpg?dl=0",
      "instructor": "Tim Buchalka, Jean-Paul Roberts, Tim Buchalka's Learn Programming Academy",
	  "rating": 4.5,
	  "price": 29.99,
    },
	{
      "id": 8,
      "name": "Learn Ethical Hacking From Scratch",
      "img": "https://dl.dropboxusercontent.com/s/wd797ohhfuijcof/11.jpg?dl=0",
      "instructor": "Zaid Sabih, z Security",
	  "rating": 4.5,
	  "price": 19.99,
    },
	{
      "id": 9,
      "name": "The Complete JavaScript Course 2020: Build Real Projects!",
      "img": "https://dl.dropboxusercontent.com/s/tgf42fbyxcvjkuh/12.jpg?dl=0",
      "instructor": "Jonas Schmedtmann",
	  "rating": 4.6,
	  "price": 39.99,
    },
	{
      "id": 10,
      "name": "Angular - The Complete Guide (2020 Edition)",
      "img": "https://dl.dropboxusercontent.com/s/w7h7bve90j7dq4r/13.jpg?dl=0",
      "instructor": "Maximilian Schwarzmüller",
	  "rating": 4.6,
	  "price": 39.99,
    },
	{
      "id": 11,
      "name": "Python for Data Science and Machine Learning Bootcamp",
      "img": "https://dl.dropboxusercontent.com/s/5opscbhjit904mk/14.jpg?dl=0",
      "instructor": "Jose Portilla",
	  "rating": 4.8,
	  "price": 9.99,
    },
	{
      "id": 12,
      "name": "The Complete Digital Marketing Course - 12 Courses in 1",
      "img": "https://dl.dropboxusercontent.com/s/2tz4s89sdjdyf59/16.jpg?dl=0",
      "instructor": "Rob Percival, Daragh Walsh, Codestars by Rob Percival",
	  "rating": 4.4,
	  "price": 19.99,
    },
	{
      "id": 13,
      "name": "The Complete Front-End Web Development Course!",
      "img": "https://dl.dropboxusercontent.com/s/cowovll78mfox4l/17.jpg?dl=0",
      "instructor": "Joseph Delgadillo, Nick Germaine",
	  "rating": 4.3,
	  "price": 9.99,
    },
	{
      "id": 14,
      "name": "The Complete Web Developer in 2020: Zero to Mastery",
      "img": "https://dl.dropboxusercontent.com/s/o447wla5ju0gvbo/18.jpg?dl=0",
      "instructor": "Andrei Neagoie",
	  "rating": 4.8,
	  "price": 9.99,
    },
	{
      "id": 15,
      "name": "The Complete SQL Bootcamp 2020: Go from Zero to Hero",
      "img": "https://dl.dropboxusercontent.com/s/sswwqan2tpe0b5b/19.jpg?dl=0",
      "instructor": "Jose Portilla",
	  "rating": 4.7,
	  "price": 9.99,
    },
];
  export default courseData;